version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: lbry-explorer
    container_name: lbry-explorer-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - lbry-explorer

  nginx:
    image: nginx:alpine
    container_name: lbry-explorer-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lbry-explorer

networks:
  lbry-explorer:
    driver: bridge
